//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repaso.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RepasodbEntities : DbContext
    {
        public RepasodbEntities()
            : base("name=RepasodbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vehiculo> vehiculo { get; set; }
        public virtual DbSet<Accesorio> Accesorio { get; set; }
    
        public virtual ObjectResult<Sp_ConsultarVehiculo_Result> Sp_ConsultarVehiculo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ConsultarVehiculo_Result>("Sp_ConsultarVehiculo");
        }
    
        public virtual ObjectResult<Sp_ConsultarVehiculo2_Result> Sp_ConsultarVehiculo2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ConsultarVehiculo2_Result>("Sp_ConsultarVehiculo2");
        }

        public System.Data.Entity.DbSet<Repaso.Models.Sp_ConsultarVehiculo2_Result> Sp_ConsultarVehiculo2_Result { get; set; }
    }
}
